#pragma once
#include "raid-detail.hpp"
#include "xoroshiro.hpp"
#include "personal-info.hpp"
#include <cstdint>
#include <vector>

// Auto-generated by bin2o from encounter table data files
extern const uint8_t enc_paldea_std_bin[];
extern const uint8_t enc_paldea_std_bin_end[];
extern const uint8_t enc_paldea_blk_bin[];
extern const uint8_t enc_paldea_blk_bin_end[];
extern const uint8_t enc_kitakami_std_bin[];
extern const uint8_t enc_kitakami_std_bin_end[];
extern const uint8_t enc_kitakami_blk_bin[];
extern const uint8_t enc_kitakami_blk_bin_end[];
extern const uint8_t enc_blueberry_std_bin[];
extern const uint8_t enc_blueberry_std_bin_end[];
extern const uint8_t enc_blueberry_blk_bin[];
extern const uint8_t enc_blueberry_blk_bin_end[];

enum class GameVersion { Scarlet, Violet };

enum class GemType : uint8_t {
    Default = 0,
    Random = 1,
    // 2-19 are specific types (type = gemType - 2)
};

inline bool gemTypeIsSpecified(GemType gem, uint8_t& outType) {
    auto v = (uint8_t)gem;
    if (v >= 2) {
        outType = v - 2;
        return true;
    }
    return false;
}

enum class AbilityPermission : uint8_t {
    Any12 = 0,
    Any12H = 1,
    OnlyFirst = 2,
    OnlySecond = 4,
    OnlyHidden = 8,
};

enum class ShinyType : uint8_t {
    Random = 0,
    Never = 1,
    Always = 2,
};

// 0x3C bytes per entry in encounter table
struct EncounterTeraTF9 {
    static constexpr int SERIALIZED_SIZE = 0x3C;

    uint16_t species;
    uint8_t form;
    uint8_t gender;
    AbilityPermission ability;
    uint8_t flawlessIVCount;
    ShinyType shiny;
    uint8_t level;
    uint16_t moves[4];
    GemType teraType;
    uint8_t index;
    uint8_t stars;
    uint8_t randRate;
    int16_t randRateMinScarlet;
    int16_t randRateMinViolet;
    uint32_t identifier;
    uint16_t extraMoves[6];
    uint8_t genderRatio;

    static inline EncounterTeraTF9 readFrom(const uint8_t* data, uint8_t personalGender) {
        auto r16 = [](const uint8_t* p) -> uint16_t { return (uint16_t)(p[0] | (p[1] << 8)); };
        auto r16s = [](const uint8_t* p) -> int16_t { return (int16_t)(p[0] | (p[1] << 8)); };
        auto r32 = [](const uint8_t* p) -> uint32_t {
            return p[0] | (p[1] << 8) | (p[2] << 16) | (p[3] << 24);
        };

        EncounterTeraTF9 e{};
        e.species           = r16(data + 0x00);
        e.form              = data[0x02];
        e.gender            = data[0x03] > 0 ? data[0x03] - 1 : 0;
        e.ability           = static_cast<AbilityPermission>(
            data[0x04] == 0 ? 0 :
            data[0x04] == 1 ? 1 :
            data[0x04] == 2 ? 2 :
            data[0x04] == 3 ? 4 :
            data[0x04] == 4 ? 8 : 0);
        e.flawlessIVCount   = data[0x05];
        e.shiny             = (ShinyType)data[0x06];
        e.level             = data[0x07];
        e.moves[0]          = r16(data + 0x08);
        e.moves[1]          = r16(data + 0x0A);
        e.moves[2]          = r16(data + 0x0C);
        e.moves[3]          = r16(data + 0x0E);
        e.teraType          = (GemType)data[0x10];
        e.index             = data[0x11];
        e.stars             = data[0x12];
        e.randRate          = data[0x13];
        e.randRateMinScarlet = r16s(data + 0x14);
        e.randRateMinViolet  = r16s(data + 0x16);
        e.identifier        = r32(data + 0x18);
        e.extraMoves[0]     = r16(data + 0x30);
        e.extraMoves[1]     = r16(data + 0x32);
        e.extraMoves[2]     = r16(data + 0x34);
        e.extraMoves[3]     = r16(data + 0x36);
        e.extraMoves[4]     = r16(data + 0x38);
        e.extraMoves[5]     = r16(data + 0x3A);
        e.genderRatio       = personalGender;

        return e;
    }
};

struct EncounterTable {
    std::vector<EncounterTeraTF9> entries;

    inline void loadFromEmbedded(const uint8_t* data, const uint8_t* data_end, const PersonalTable& pt) {
        size_t size = (size_t)(data_end - data);
        int count = (int)(size / EncounterTeraTF9::SERIALIZED_SIZE);
        entries.clear();
        entries.reserve(count);

        for (int i = 0; i < count; i++) {
            const uint8_t* ptr = data + i * EncounterTeraTF9::SERIALIZED_SIZE;
            uint16_t species = (uint16_t)(ptr[0] | (ptr[1] << 8));
            uint8_t form = ptr[0x02];
            auto pi = pt.getFormEntry(species, form);
            entries.push_back(EncounterTeraTF9::readFrom(ptr, pi.gender()));
        }
    }
};

// Rate totals from PKHeX EncounterTera9.cs
namespace RateTotals {
    inline int16_t paldeaSL(int stars) {
        constexpr int16_t t[] = {0, 5800, 5300, 7400, 8800, 9100, 6500};
        return (stars >= 1 && stars <= 6) ? t[stars] : 0;
    }
    inline int16_t paldeaVL(int stars) {
        constexpr int16_t t[] = {0, 5800, 5300, 7400, 8700, 9100, 6500};
        return (stars >= 1 && stars <= 6) ? t[stars] : 0;
    }
    inline int16_t kitakamiSL(int stars) {
        constexpr int16_t t[] = {0, 1500, 1500, 2500, 2100, 2250, 2475};
        return (stars >= 1 && stars <= 6) ? t[stars] : 0;
    }
    inline int16_t kitakamiVL(int stars) {
        constexpr int16_t t[] = {0, 1500, 1500, 2500, 2100, 2250, 2574};
        return (stars >= 1 && stars <= 6) ? t[stars] : 0;
    }
    inline int16_t blueberry(int stars) {
        constexpr int16_t t[] = {0, 1100, 1100, 2000, 1900, 2100, 2600};
        return (stars >= 1 && stars <= 6) ? t[stars] : 0;
    }

    inline int16_t getTotal(int stars, TeraRaidMapParent map, GameVersion ver) {
        if (ver == GameVersion::Scarlet) {
            switch (map) {
                case TeraRaidMapParent::Paldea:    return paldeaSL(stars);
                case TeraRaidMapParent::Kitakami:   return kitakamiSL(stars);
                case TeraRaidMapParent::Blueberry:  return blueberry(stars);
            }
        } else {
            switch (map) {
                case TeraRaidMapParent::Paldea:    return paldeaVL(stars);
                case TeraRaidMapParent::Kitakami:   return kitakamiVL(stars);
                case TeraRaidMapParent::Blueberry:  return blueberry(stars);
            }
        }
        return 0;
    }
}

inline uint8_t getSeedStars(Xoroshiro128Plus& xoro, GameProgress progress) {
    auto rand = xoro.nextInt(100);
    switch (progress) {
        case GameProgress::Unlocked6Stars:
            if (rand > 70) return 5;
            if (rand > 30) return 4;
            return 3;
        case GameProgress::Unlocked5Stars:
            if (rand > 75) return 5;
            if (rand > 40) return 4;
            return 3;
        case GameProgress::Unlocked4Stars:
            if (rand > 70) return 4;
            if (rand > 40) return 3;
            if (rand > 20) return 2;
            return 1;
        case GameProgress::Unlocked3Stars:
            if (rand > 70) return 3;
            if (rand > 30) return 2;
            return 1;
        default:
            if (rand > 80) return 2;
            return 1;
    }
}

inline const EncounterTeraTF9* getEncounterFromSeed(
    uint32_t seed,
    const std::vector<EncounterTeraTF9>& encounters,
    GameVersion version,
    GameProgress progress,
    RaidContent content,
    TeraRaidMapParent map)
{
    auto xoro = Xoroshiro128Plus(seed);

    uint8_t randStars;
    if (content == RaidContent::Standard) {
        randStars = getSeedStars(xoro, progress);
    } else {
        randStars = 6;
    }

    int16_t maxRate = RateTotals::getTotal(randStars, map, version);
    if (maxRate <= 0) return nullptr;

    auto rateRand = (int)xoro.nextInt((uint64_t)maxRate);

    for (auto& enc : encounters) {
        if (enc.stars != randStars)
            continue;

        int16_t minRate = (version == GameVersion::Scarlet)
            ? enc.randRateMinScarlet
            : enc.randRateMinViolet;

        if (minRate < 0)
            continue;

        if ((uint32_t)(rateRand - minRate) < enc.randRate)
            return &enc;
    }

    return nullptr;
}
