#pragma once
#include "raid-calc.hpp"
#include <cstdint>
#include <string>
#include <vector>
#include <csight-core.h>

// Auto-generated by bin2o
extern const uint8_t natures_en_bin[];
extern const uint8_t natures_en_bin_end[];
extern const uint8_t types_en_bin[];
extern const uint8_t types_en_bin_end[];

namespace TeraText {

inline std::vector<std::string> parseLines(const uint8_t* data, size_t size) {
    std::vector<std::string> lines;
    std::string current;
    for (uint32_t i = 0; i < size; i++) {
        if (data[i] == '\n') {
            if (!current.empty() && current.back() == '\r')
                current.pop_back();
            lines.push_back(current);
            current.clear();
        } else {
            current += (char)data[i];
        }
    }
    if (!current.empty())
        lines.push_back(current);
    return lines;
}

inline std::string getSpeciesName(uint16_t species) {
    char buf[32];
    csight::get_species_string(species, buf, sizeof(buf));
    return std::string(buf);
}

inline std::string getNatureName(uint8_t nature) {
    static std::vector<std::string> names;
    if (names.empty())
        names = parseLines(natures_en_bin, (size_t)(natures_en_bin_end - natures_en_bin));
    if (nature < names.size())
        return names[nature];
    return std::to_string(nature);
}

inline std::string getTypeName(uint8_t type) {
    static std::vector<std::string> names;
    if (names.empty())
        names = parseLines(types_en_bin, (size_t)(types_en_bin_end - types_en_bin));
    if (type < names.size())
        return names[type];
    return std::to_string(type);
}

inline std::string getStarsString(uint8_t stars) {
    std::string s;
    for (int i = 0; i < stars; i++)
        s += "\u2605";
    return s;
}

inline std::string getShinyString(TeraShiny shiny) {
    switch (shiny) {
        case TeraShiny::Star:   return "\u2605";
        case TeraShiny::Square: return "\u25A0";
        default:                return "";
    }
}

inline std::string getGenderString(Gender gender) {
    switch (gender) {
        case Gender::Male:       return "\u2642";
        case Gender::Female:     return "\u2640";
        case Gender::Genderless: return "";
    }
    return "";
}

inline std::string formatIVs(const int ivs[6]) {
    std::string s;
    for (int i = 0; i < 6; i++) {
        if (i > 0) s += "/";
        s += std::to_string(ivs[i]);
    }
    return s;
}

} // namespace TeraText
